### PR TITLE
Complete Angular 10 upgrade

### PR DESCRIPTION
**Pull request by reda-alaoui**
This change follows:
* #1008
* #1003

It completes the Angular 10 upgrade and fixes the project build.

### CODE REVIEW

**Comment by reda-alaoui** [comment]
Build is now green. Waiting for review.

**Comment by vamidi** [comment]
Would be awesome if this get pushed for the latest release.

**Comment by pascalklesse** [comment]
It would be nice if it could be published.

**Comment by reda-alaoui** [comment]
Hello?

**Comment by chriscarpenter12** [comment]
Can someone merge this fix please?

**Comment by reda-alaoui** [comment]
Ping :)

**Comment by reda-alaoui** [comment]
Ping :)

**Comment by reda-alaoui** [comment]
Is there something I can do to ease the merge of this fix?

**Comment by matharu007** [comment]
Someone plz confirm if the fix is merged and ready to use in ng 11

**Comment by Lertis** [comment]
> Someone plz confirm if the fix is merged and ready to use in ng 11

Interested too.

**Comment by Qsaws** [comment]
Any chance for this to be merged for a new release ?

**Review by peteichuk — APPROVED** [review]

**Comment by Lertis** [comment]
Waiting for the ```Merge`` button to be pressed

**Comment by jc0rtes** [comment]
ward

**Comment by fhebuterne** [comment]
@jziggas Hi, could you check this pull request please ?

**Comment by jziggas** [comment]
@fhebuterne I don't have access to this repo. Nothing I can do.

**Comment by frknfndk** [comment]
Hello, we are waiting for this merge. We are getting this error:
image

**Comment by prinju-experion** [comment]
someone please merge this
:(

**Comment by rodizipa** [comment]
pong

**Comment by prinju-experion** [comment]
Marko...

**Comment by odiazjs** [comment]
can this be merge please? @reda-alaoui

**Comment by reda-alaoui** [comment]
@odiazjs , I do not have any permission on this repository ...

**Comment by odiazjs** [comment]
@reda-alaoui oh well, `skipLibCheck` it is then...

**Review by valorkin — APPROVED** [review]

**Comment by Xaivteev** [comment]
Can this be released on npm?

**Comment by valorkin** [comment]
@djessenb yes, this week we will be merging, reviewing releasing, new versions

**Comment by kovalforpublic** [comment]
@valorkin any update on releasing npm version?

**Comment by nikhil-kapoor-quo** [comment]
any updates ?

**Pull request merged**
