### PR TITLE
Upgrade ng2-dragula to use angular 2.0.0-rc.1

### PR DESCRIPTION
**Pull request by xtiancapil**
Hi Guys, I've upgraded the angular dependency to ~~2.0.0-rc.0~~ 2.0.0-rc.1, please let me know if it looks OK to you.

### CODE REVIEW

**Comment by Blackbaud-PaulCrowder** [comment]
Can we get this merged in?  It looks like this is jamming a lot of people up.

**Comment by jan-zajic** [comment]
please @valorkin, can you look at this?

**Comment by valorkin** [comment]
Great work! I will test it locally and publish asap

**Comment by valorkin** [comment]
yeap, I will udpate it
today, latest tomorrow

**Comment by valorkin** [comment]
only 2 small PRs left to merge
and I will get to this one:)
https://github.com/valor-software/ng2-file-upload/pulls

sorry for delay

**Comment by valorkin** [comment]
Merged with https://github.com/valor-software/ng2-dragula/commit/f3ff82c79a5008dc05d6f35512c97b2bfce3c362
thanks again!

If you want to have a write access here, drop me an email

**Comment by xtiancapil** [comment]
@valorkin no problem! thanks for taking the time in making this!

**Comment by jan-zajic** [comment]
@valorkin, @xtiancapil thank you a lot

**Pull request closed without merging**
