### PR TITLE
Update package.json

### PR DESCRIPTION
**Pull request by rafalolbracht**
I've changed @angular dependencies. My goal was to get rid of an error during a package installation process: "Invalid tag name ">=^16.0.0 <=^17.0.0" of package "@angular/animations@>=^16.0.0 <=^17.0.0": Tags may not have any characters that encodeURIComponent encodes."

### CODE REVIEW

**Comment by m-burger** [comment]
Could we have an update on this PR please ? This is required when using angular 17+ versions. Thank you

**Comment by CJHunter91** [comment]
I'll also post a request to get this merged in for 17+

**Comment by MattJWhite** [comment]
@CJHunter91 is there any update on when this will be completed? Currently trying to upgrade an application to 17 and not keen on using the workaround posted in some of the other issues

**Comment by MattJWhite** [comment]
@valorkin Is there any update on when this will be merged in to fully resolve #1103? I'm in the process of upgrading an application to Angular 17 and unfortunately can't make use of the workaround provided there

**Review by valorkin — APPROVED** [review]

**Comment by Blackbaud-SteveBrush** [comment]
@valorkin Thank you!

**Pull request merged**
