### PR TITLE
Emit model data with `dropModel`

### PR DESCRIPTION
**Pull request by spongessuck**
Right now, dropModel just passes the bag name and the elements involved in the drop, which is not very useful; I want to know what the underlying data is.

In the source lib, the `dropModel` event passes an array like other Dragula events, but since `dropModel` is a new event created by this lib, I think it's OK to divert from Dragula and pass an object instead, since it's easier to work with. This is a breaking change, but the additional data I added to the emitted object could easily be added to an emitted array instead.

In any case, this PR changes `dropModel` to pass the dropped elements data, the target model (array) and source model (array) in addition to the elements and bag name.

If you like the idea but don't want a breaking change, I can switch it back to an array and just append these data to it.

### CODE REVIEW

**Comment by cormacrelf** [comment]
I'd rather not have the breaking change, but I'm sure we could type the event handlers better in general without moving away from function arguments or making using ng2-dragula vastly different from dragula when we're really just a wrapper.

But this does warrant some rethinking of how dragulaModel and its events work. Currently it only works for mutable arrays, but I'd prefer to handle the insertion/deletion of models from those lists myself. This is a good start, but this might be reworked to make the array mutation optional and replaceable. An event which modifies your model arrays and then just tells you what it already did isn't much of an improvement.

**Comment by spongessuck** [comment]
I think that all makes sense. I'm not sure how you'd go about typing an array parameter, though.

As far as mutating the array, maybe there could be another attribute like `@Input() immutable: boolean` that can you can set to make the ng-dragula assume that you're going to handle inserting/deleting in the model arrays. Or it could check if the model is an Immutable.js type and do it automatically?

**Comment by cormacrelf** [comment]
As for typing arrays, the rxjs link is to something I haven't figured out about Observable<A>.withLatestFrom(b: B, ([a,b]) => {...}) where it can pin down what the parameters a and b are in the function. 

The spirit of dragula is good default implementations you can override to do more advanced stuff. Not gonna check for Immutable, shouldn't need that. This all looks a lot easier to use if you have event handlers right next to your dragula directive filtered to your container. I might rework some of this.

**Comment by spongessuck** [comment]
I think the RxJS example just works like you can have up to 6 observables with specific types as parameters, or you can have any number of `any`-typed observables.

I think the tuple will work perfectly. It adds typing and is accessed like an array; it should be a drop-in replacement for the current implementation.

**Comment by cormacrelf** [comment]
👍 for tuples.

**Comment by RickyRoller** [comment]
Would love to see this! For the project I'm working on, not having the data of the object that was dropped is pretty debilitating.

**Comment by mschering** [comment]
Will this be merged any time soon?
It seems to be a must have!

**Comment by ranton** [comment]
please merge :)

**Comment by johannesjo** [comment]
I also have a need for this one. Currently I'm unable to find a way to sync my observable in a proper way to the changes made by ng2-dragular.

**Comment by yangwen2** [comment]
what has been the work around to gain access to the object that was dragged?

I'm currently using angular's mouseover event on the dragged item to set a class level reference to the item's data.  This reference is then access in the dropModel call back.  Anyone else using a similar pattern?

**Comment by cormacrelf** [comment]
I'm rewriting this into v2. It will be slightly different, and since I'm doing other breaking changes, it will be the better way.

- Improved dispatching mechanism to allow users to go `drag("SOME_TYPE").subscribe(...)` or just `drag()` for any type.
- Typed objects, not arrays. `drag().subscribe(({ el, source }) => { ... })` is great.
- dropModel will includes the model data (the commit I'm about to publish doesn't quite achieve this but it's close)

- (Note that type === v1 'bag name'. Bags are too confusing, people think they are the same thing as containers even though a bag is an entirely different data structure. Also we don't even have bags, we have arrays of drakes.)

**Comment by cormacrelf** [comment]
Also since anyone here (the COOL thread) might have some insight, does it make sense to stop modifying arrays and require two-way binding to do that by default?

like

```html
<div dragula="CAT" [(dragulaModel)]="myModel">
   ngFor myModel...
</div>
```

That would enable people to use it with, e.g. `@ngrx/store` more easily.

```html
<div *ngIf="myModel$|async as ms" dragula="CAT" [dragulaModel]="ms">
   ...
</div>
```

```typescript
this.subs.add(
    this.dragulaService.dropModel("CAT").subscribe(({ item, sourceModel, targetModel }) => {
        // TODO: SEE QUESTION
        this.store.dispatch(new DropAction(item, sourceModel, targetModel));
    });
);
```

The big question would be whether to do the splicing for you, or to let you handle that yourself.

**Comment by spongessuck** [comment]
Splicing it makes sense to me; I wouldn't want to have to subscribe to changes to update the model when two-way binding could do it, and if I wanted to do it manually I could just bind `[dragulaModel]` and handle the change event myself.

**Comment by cormacrelf** [comment]
Implemented in 53f8d415a28722b2c0e8099c9a0dff78effc50af, check it out.

**Pull request closed without merging**
