### PR TITLE
Fix 1003 Angular 10 Compatibility

### PR DESCRIPTION
**Pull request by jziggas**

### CODE REVIEW

**Comment by valorkin** [comment]
thanks for helping out

**Comment by sguiheux** [comment]
Possible to have a release with the fix ? :) 
Thanks a lot

**Comment by EmaGht** [comment]
After a month from the original request of a release with this fix...

I really need this too. Could you please?
Thanks!

**Comment by valorkin** [comment]
This was released a while ago, as far as remember version 6+
@daniloff200 cc

**Comment by EmaGht** [comment]
@valorkin There is no version 6+ of ng2 dragula on npm. The last version available (2.1.1) still fails on NG10 with this error:

image

**Comment by valorkin** [comment]
My bad, sorry. Thought I was responding in ngx bootstrap repo

**Comment by EmaGht** [comment]
Sure, @valorkin, no problem.
Just a heads up tho, in the readme file it reads "**Official** Angular wrapper", but we are almost at NG11 and this library still doesn't support NG10 so it doesn't really sound "**Official**". When i want to switch my company repository to the new NG version should i trust the fact this library gets updated or am i better of branching it and mantaining it?
Thanks again!

**Comment by valorkin** [comment]
I can give you a maintenance access if you wish and add to our slack so you could me. Published was automatical on merge to master

**Comment by EmaGht** [comment]
I'd be happy to help.

Only thing left to understand is why it didn't automatically publish after the merge of this PR

**Comment by jziggas** [comment]
I think because the build failed due to the demo code needing to be updated.

**Comment by EmaGht** [comment]
Well, it all makes sense now.

I'm okay with either becoming a maintainer or just waiting for the library to be fixed, what suits you guys best.

**Comment by valorkin** [comment]
BUILD ERROR
`src/components/dragula.module.ts(10,21): error TS2315: Type 'ModuleWithProviders' is not generic`

if this will be fixed, and new version could be released

**Comment by reda-alaoui** [comment]
Hello, @valorkin,

I fixed it here => https://github.com/valor-software/ng2-dragula/pull/1023

**Comment by matharu007** [comment]
@valorkin: can you plz confirm if the fix for the BUILD ERROR is merged and release. I am getting the same error using ng 11

**Pull request merged**
