### PR TITLE
Set drag container as mirrorContainer

### PR DESCRIPTION
**Pull request by iblank**
Sets the mirrorContainer option to the nativeElement of the directive. This makes it possible to easily style the mirror using shadow DOM encapsulation.

### CODE REVIEW

**Comment by cormacrelf** [comment]
I'm positive this will break a LOT of code using ng2-dragula. The default is to append mirror elements to the body, and everybody writes mirror-targeting CSS with this in mind.

1. Are you certain this lets you do what you want with the shadow DOM?
2. Would it also be acceptable to simply make it easier to configure Dragula this way, rather than making it the new default?

**Comment by iblank** [comment]
Good points. Setting it as an option in ng2-dragula would be best and
wouldn't mess with existing projects. I'll revise it some time soon.

On Jun 14, 2017 7:59 PM, "Cormac Relf" <notifications@github.com> wrote:

I'm positive this will break a LOT of code using ng2-dragula. The default
is to append mirror elements to the body, and everybody writes
mirror-targeting CSS with this in mind.

   1. Are you certain this lets you do what you want with the shadow DOM?
   2. Would it also be acceptable to simply make it easier to configure
   Dragula this way, rather than making it the new default?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/valor-software/ng2-dragula/pull/741#issuecomment-308590900>,
or mute the thread

**Comment by iblank** [comment]
@cormacrelf Let me know what you think of this change. Now the mirror defaults to the body, but can be set to the local element with the dragulaLocalMirror attribute. Also, I would've updated the unit tests for this change, but there currently aren't any place at all for the directive. I'll see what I can do about updating that spec file.

Example usage:
`<div class='container' [dragula]='"first-bag"' dragulaLocalMirror>...</div>`

**Comment by axtho** [comment]
Guys, I wonder whether this is going to make any difference, since none of the recent PRs have been accepted. If you look into the closed PR list, going back 6 months, just a couple of PRs have been merged. I really wonder whether this is being actively maintained. Why not fork this, name it ngx-dragula, and move on from here?

**Comment by cormacrelf** [comment]
Sorry this took so long. I’ve been on other projects, and even if I merge things, I can’t release them. But this was good.

**Comment by cormacrelf** [comment]
Note that I removed the feature from v2. Expand the commit message just there to see why.

**Pull request merged**
