### PR TITLE
Fix installing ng2-dracula in a project without typings.json

### PR DESCRIPTION
**Pull request by ggirou**
Installing ng2-dracula in a fresh new project without typings.json failed:

	npm init
	npm install ng2-dragula --save-dev

	> ng2-dragula@1.1.9 postinstall ***********\test\node_modules\ng2-dragula
	> typings install

	typings ERR! message Unable to resolve Typings dependencies
	typings ERR! caused by Unable to find "typings.json" from "***********\test\node_modules\ng2-dragula"

	typings ERR! cwd ***********\test\node_modules\ng2-dragula
	typings ERR! system Windows_NT 6.1.7601
	typings ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Me\\AppData\\Roaming\\npm\\node_modules\\typings\\dist\\bin.js" "install"
	typings ERR! node -v v4.4.1
	typings ERR! typings -v 0.8.1

	typings ERR! If you need help, you may report this error at:
	typings ERR!   <https://github.com/typings/typings/issues>
	npm WARN ng2-dragula@1.1.9 requires a peer of @angular/common@^2.0.0-rc.1 but none was installed.
	npm WARN ng2-dragula@1.1.9 requires a peer of @angular/core@^2.0.0-rc.1 but none was installed.
	npm WARN test@1.0.0 No description
	npm WARN test@1.0.0 No repository field.
	npm ERR! Windows_NT 6.1.7601
	npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Me\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "ng2-dragula" "--save-dev"
	npm ERR! node v4.4.1
	npm ERR! npm  v3.8.9

### CODE REVIEW

**Comment by ggirou** [comment]
BTW, I can't use typings because I'm behind a corporate proxy, so I'm handling definition files differently.

**Comment by jhiemer** [comment]
Could we merge this, that one is able to install ng2-dragula again?

**Comment by ggirou** [comment]
I published it then installed it and noticed that typings isn't run anymore :)

```
$ npm init

$ # Install peer dependencies
$ npm install @angular/common@2.0.0-rc.1 @angular/core@2.0.0-rc.1 rxjs@5.0.0-beta.6 zone.js@0.6.12

$ npm install https://github.com/ggirou/ng2-dragula/releases/download/v1.1.11/ng2-dragula-1.1.11.tgz
test@1.0.0 /Users/guillaumegirou/dev/test
└── ng2-dragula@1.1.11  extraneous
```

`npm install ../path/to/ng2-dragula` doesn't work since [`prepublish` is run on local `npm install`](https://docs.npmjs.com/misc/scripts)...

**Comment by valorkin** [comment]
https://github.com/npm/npm/issues/3059

but we can try :)

**Comment by jhiemer** [comment]
We need to create a new release for ng2-dragula (1.1.10) as the current 1.1.9 still fails during install.

**Comment by valorkin** [comment]
published

**Pull request merged**
